config/routes.rb
FOBH::Application.routes.draw do
  root :to => 'pages#home'

  match '/conservation', :to => 'pages#conservation'

  match '/funding',    :to =>  'pages#funding'

  match '/education',    :to =>  'pages#education'

  match '/fun',    :to =>  'pages#fun'

  match '/news',    :to =>  'pages#news'

  match '/publications',    :to => 'pages#publications'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def conservation
    @title = "Conservation"
  end

  def funding
    @title = "Funding"
  end

  def education
    @title = "Education"
  end

  def fun
    @title = "Fun"
  end

  def news
    @title = "News"
  end

  def publications
    @title = "Publications"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "The Friends of Box Hill"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<header>
  <h1></h1>
</header>

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Conservation", conservation_path %></li>
    <li><%= link_to "Funding", funding_path %></li>
    <li><%= link_to "Education", education_path %></li>
    <li><%= link_to "Fun", fun_path %></li>
    <li><%= link_to "News", news_path %></li>
    <li><%= link_to "Publications", publications_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   <article>
     <%= render 'layouts/header' %>
     <%= render 'layouts/navigation' %>

       <%= yield %>

   </article>



</body>
</html>

app/views/pages/conservation.html.erb
<section>
  <p>
    Phasellus posuere ultrices enim sed pharetra. Praesent fermentum, elit dapibus vulputate tempor,
    nisi ligula lobortis sem, id elementum est neque non quam. Fusce vitae lacus sit amet orci bibendum
    tempor. Vivamus id purus in lacus gravida auctor sit amet nec leo. Aliquam lacinia sollicitudin mauris
    at volutpat. Phasellus id consectetur nisi. Praesent malesuada sagittis quam, id dapibus nunc rutrum
    ac. Nullam eu dui orci. Integer egestas feugiat nibh, vel interdum leo auctor placerat. Nulla
    pellentesque lorem non augue aliquam nec pharetra lectus sodales.
  </p>
  <p>
    Aliquam est nulla, tristique et pharetra ut, hendrerit a leo. Vestibulum ante ipsum primis in
    faucibus orci luctus et ultrices posuere cubilia Curae; Etiam felis ligula, sodales eu tempor id,
    vulputate in metus. Phasellus lorem tellus, viverra non suscipit et, dignissim at magna. Vivamus
    convallis suscipit nunc tincidunt porttitor. Ut imperdiet risus eget metus fermentum mattis eget
    sit amet neque. Ut tempus accumsan laoreet. Morbi turpis sapien, euismod ac aliquet vitae, accumsan
    sed nisl. Mauris in diam diam, vitae elementum sapien. Sed urna turpis, vestibulum vel volutpat vel,
    fermentum in urna. Aenean placerat luctus diam, in dignissim quam luctus in. Pellentesque sit
    amet enim ipsum. Etiam justo arcu, tempus blandit molestie ut, luctus a mi.
  </p>
</section>

app/views/pages/education.html.erb
<section>
  <p>
    Ut viverra hendrerit est, vel convallis sem posuere sed. Nam ac sapien elit, vitae mattis nunc.
    Nullam sit amet blandit lectus. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent
    per conubia nostra, per inceptos himenaeos. Pellentesque vestibulum lobortis neque, ac pharetra
    dui facilisis a. Aliquam erat volutpat. Morbi venenatis erat ut lectus facilisis auctor.
    Ut suscipit, tellus sit amet venenatis pellentesque, urna lectus ornare sapien, vel vulputate
    risus arcu eu turpis. Aliquam sit amet risus nisi, et ultrices tellus. Proin ac dignissim leo.
    Nam pretium pellentesque risus, sit amet eleifend diam sodales eget. In ac consequat libero.
    Nunc sed consequat augue.
  </p>
  <p>
    In pulvinar pretium tortor, a pretium tortor porttitor eget. Morbi sit amet consequat libero.
    Nam luctus lectus a leo aliquet rhoncus. Vestibulum purus neque, accumsan vel interdum sed,
    ultrices ut risus. Phasellus lobortis posuere rhoncus. Suspendisse facilisis nunc vitae ante
    varius non malesuada lacus sagittis. Pellentesque cursus vulputate libero et semper.
  </p>
</section>

app/views/pages/fun.html.erb
<section>
  <p>
    Aenean non massa magna, sed vulputate lacus. Duis malesuada quam ut sapien ultrices ut blandit
    nulla volutpat. Suspendisse lobortis tempus metus, eget ornare ipsum sagittis quis. Nunc velit
    tellus, fermentum at ultricies eu, viverra vel lectus. Curabitur elementum leo sit amet eros dapibus
    sed bibendum dolor tristique. Ut metus ligula, aliquam ut hendrerit at, placerat et elit. Vivamus
    ligula dui, vehicula at eleifend nec, vestibulum et diam.
  </p>
  <p>
    Phasellus convallis, diam eu varius faucibus, lacus augue mattis massa, ac adipiscing sapien
    neque a dolor. Nullam id porttitor diam. Nam mattis ante at erat facilisis quis posuere mauris
    cursus. Mauris diam nibh, pulvinar faucibus iaculis eu, accumsan sed ipsum. Pellentesque nec
    lorem leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
    Proin eu aliquet purus. Sed ipsum magna, fermentum nec tristique ut, laoreet sed metus. Ut
    felis turpis, mollis fringilla rutrum quis, suscipit non erat. Sed quis orci leo, fermentum
    porttitor augue. Nulla aliquet leo ut velit tristique eu malesuada leo tincidunt.
  </p>
</section>

app/views/pages/funding.html.erb
<section>
  <p>
    Nam at metus augue. Cras aliquam condimentum est et fringilla. Phasellus lorem nibh, eleifend non
    gravida ut, blandit id augue. Vestibulum pretium turpis eu libero luctus id semper mauris placerat.
    Phasellus massa eros, tempor eu vehicula sed, euismod eu mauris. Vestibulum aliquet ante in velit
    semper sed tristique nulla blandit. Duis ut neque et eros placerat rhoncus.
  </p>
  <p>
    Nulla facilisi. Integer auctor laoreet congue. Aenean sit amet purus nisl. Donec molestie hendrerit
    porta. In gravida felis non libero dapibus pretium eleifend dolor lacinia. In faucibus, tortor et
    euismod pellentesque, nunc urna venenatis urna, in adipiscing turpis purus in nunc. Aliquam at
    libero ante, ut aliquet dui. Suspendisse ultricies orci nec tellus fringilla ac congue tortor
    scelerisque. Morbi pharetra nibh et turpis mollis consequat. Ut pulvinar urna in ipsum lacinia
    malesuada. Nam et leo et velit eleifend tristique. Aenean id odio lectus, vel dictum diam.
    Nullam euismod lectus vel risus convallis scelerisque. Sed porttitor iaculis luctus.
  </p>
</section>

app/views/pages/home.html.erb
<section id='home'>
  <h1>Friend's of Box Hill</h1>
  <%= image_tag("Grey_Heron.jpg", :id => "gallery") %>
</section>

<section class="sidebar" id="left">
  <h1>About Us</h1>
  <p>
    <strong>Box Hill</strong> is one of the best known features in the North Downs.
    Only 20 miles from the centre of London,
    it is a haven of natural beauty with more than a million visitors every year. Those numbers mean that
    special care is necessary to protect its many rare species of flora and fauna.
    The Friends of Box Hill is an independent association, affiliated to the Campaign to Protect Rural England.
    It is made up of people who love the Hill, and keep a close watch on everything that affects it.
   </p>
</section>

<section class="sidebar" id="right">
  <h1>Find out more!</h1>
  <p>
    You can join us using this application form. To find out more (including about forthcoming events and
    news from the Hill) have a look at the blog or please ring 01306 885502, or email, or write to: <br><br>
      The Friends of Box Hill,  <br>
      c/o the National Trust, <br>
      Warren Farm Barn, <br>
      Headley Lane, Mickleham, Dorking, RH5 6DG.  <br>
   </p>
</section>

app/views/pages/news.html.erb
<section>
  <p>
    Praesent aliquam, leo vel interdum rhoncus, purus enim molestie mi, ut interdum libero mi
    venenatis elit. Donec massa odio, facilisis et dignissim et, cursus non ante. In at leo libero.
    Duis mi nisi, ornare eu convallis ac, tempus et lorem. Aliquam erat volutpat. Proin eu tortor vel
    nisi congue porttitor quis vitae nisl. Pellentesque dictum ante et est laoreet lobortis.
  </p>
  <p>
    Etiam dui libero, vestibulum sed elementum eu, cursus molestie risus. In sed quam eros, in
    tincidunt magna. Integer sem tellus, vulputate id sodales id, commodo ac est. Cras suscipit
    elementum elit vitae sagittis. Vestibulum ut porttitor tellus. Nullam porttitor euismod augue
    vel suscipit. Phasellus tincidunt, nisl quis tincidunt ultricies, felis mi blandit est, eget
    pellentesque augue magna a ligula. Pellentesque nec massa mauris, quis auctor sem. Nulla leo justo,
    bibendum ac placerat non, dapibus non orci. Aliquam faucibus enim eget nulla consectetur consectetur
    dignissim sed purus. Proin ultricies ornare augue porttitor sodales. Duis at felis urna, ut sodales
    quam. Maecenas vulputate aliquet eros, non iaculis tellus auctor eu.
  </p>
</section>

app/views/pages/publications.html.erb
<section>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mi velit, tempor a sagittis nec, sagittis
    eu est. Proin viverra elementum molestie. Etiam sollicitudin sagittis ligula a blandit. Duis nec hendrerit
    nunc. Duis nisl turpis, euismod sed varius sed, mattis et tortor. Vestibulum pellentesque facilisis nulla
    et dapibus. Praesent nec sem in massa feugiat gravida. Nulla id felis a felis molestie accumsan. Ut id
    magna nisi, sit amet egestas arcu.
  </p>
  <p>
    Sed urna est, vulputate quis aliquet vel, rhoncus et augue. Praesent mauris libero, accumsan et tristique
    mollis, malesuada id odio. Nullam pharetra dolor non orci euismod at viverra mauris viverra. Etiam pulvinar
    leo in libero pharetra tristique. Donec adipiscing pretium congue. Suspendisse libero lorem, dictum vitae
    tristique nec, adipiscing in leo. Nunc venenatis gravida leo, quis sodales magna sollicitudin eu. In
    sagittis libero et est sollicitudin a facilisis risus posuere. Pellentesque quis massa ut neque venenatis
    vulputate ultrices elementum diam. Suspendisse mattis elit nec enim vehicula bibendum. Fusce accumsan
    molestie arcu at ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
    turpis egestas. Quisque faucibus malesuada imperdiet. Sed fermentum vehicula porttitor.
  </p>
</section>